apiVersion: v1
kind: ConfigMap
metadata:
  name: dvsaidevopsnov
  namespace: dvsaidevopsnov-sit
  labels:
    app: dvsaidevopsnov
    costcenter: dvsaidevops
data:
  APP_ENV: production
  LOG_LEVEL: info
  API_URL: https://api.example.com
---
