apiVersion: v1
kind: ConfigMap
metadata:
  name: dvsaidevopsb1
  namespace: dvsaidevopsb1-dev
  labels:
    app: dvsaidevopsb1
    costcenter: dvsaidevops
data:
  APP_ENV: production
  LOG_LEVEL: info
  API_URL: https://api.example.com
---
